# Generated by Django 3.2 on 2021-06-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210625_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_adress',
            new_name='billing_address',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.user'),
            preserve_default=False,
        ),
    ]
